# Generated by Django 4.2.23 on 2025-08-19 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_items_json', models.JSONField()),
                ('total_calories', models.FloatField()),
                ('total_carbohydrates_g', models.FloatField()),
                ('total_protein_g', models.FloatField()),
                ('total_fat_g', models.FloatField()),
                ('health_index', models.FloatField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
